on:
  workflow_dispatch:
    inputs: {}

jobs:
  test:
    runs-on: ${{ matrix.os.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64

    steps:
    - uses: actions/checkout@v1

    - name: test
      run: dotnet test BatEscaper.Test